<?php

namespace backend\modules\products\controllers;

use backend\controllers\AuthController;
use backend\controllers\CRUDController;
use backend\models\BullionType;
use developeruz\db_rbac\behaviors\AccessBehavior;
use Yii;
use backend\models\BullionTypeDescription;
use backend\models\search\BullionTypeDescriptionSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BullionTypeDescriptionController implements the CRUD actions for BullionTypeDescription model.
 */
class BullionTypeDescriptionController extends CRUDController
{

    public function init()
    {
        $this->beanClass = BullionTypeDescription::className();
        $this->beanSearchClass = BullionTypeDescriptionSearch::className();
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * Creates a new BullionTypeDescription model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $extraParams = [
            'bullions' => BullionTypeDescription::getBullionDropdown()
        ];
        return parent::actionCreate($extraParams);
    }

    /**
     * Updates an existing BullionTypeDescription model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $extraParams = [
            'bullions' => BullionTypeDescription::getBullionDropdown()
        ];
        return parent::actionUpdate($id, false, $extraParams);
    }
}
